apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-app
  labels:
    app: logger-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger-app
  template:
    metadata:
      labels:
        app: logger-app
    spec:
      containers:
        - name: logger-app
          image: abychkov117/logger:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: logger-app-service
spec:
  selector:
    app: logger-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080